/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{

  public partial class Category : TBase
  {
    private double _v;
    private string _color;
    private bool _hidden;

    public double V
    {
      get
      {
        return _v;
      }
      set
      {
        __isset.v = true;
        this._v = value;
      }
    }

    public string Color
    {
      get
      {
        return _color;
      }
      set
      {
        __isset.color = true;
        this._color = value;
      }
    }

    public bool Hidden
    {
      get
      {
        return _hidden;
      }
      set
      {
        __isset.hidden = true;
        this._hidden = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool v;
      public bool color;
      public bool hidden;
    }

    public Category()
    {
    }

    public Category DeepCopy()
    {
      var tmp124 = new Category();
      if(__isset.v)
      {
        tmp124.V = this.V;
      }
      tmp124.__isset.v = this.__isset.v;
      if((Color != null) && __isset.color)
      {
        tmp124.Color = this.Color;
      }
      tmp124.__isset.color = this.__isset.color;
      if(__isset.hidden)
      {
        tmp124.Hidden = this.Hidden;
      }
      tmp124.__isset.hidden = this.__isset.hidden;
      return tmp124;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Double)
              {
                V = await iprot.ReadDoubleAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Color = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Bool)
              {
                Hidden = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp125 = new TStruct("Category");
        await oprot.WriteStructBeginAsync(tmp125, cancellationToken);
        var tmp126 = new TField();
        if(__isset.v)
        {
          tmp126.Name = "v";
          tmp126.Type = TType.Double;
          tmp126.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp126, cancellationToken);
          await oprot.WriteDoubleAsync(V, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Color != null) && __isset.color)
        {
          tmp126.Name = "color";
          tmp126.Type = TType.String;
          tmp126.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp126, cancellationToken);
          await oprot.WriteStringAsync(Color, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.hidden)
        {
          tmp126.Name = "hidden";
          tmp126.Type = TType.Bool;
          tmp126.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp126, cancellationToken);
          await oprot.WriteBoolAsync(Hidden, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Category other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.v == other.__isset.v) && ((!__isset.v) || (global::System.Object.Equals(V, other.V))))
        && ((__isset.color == other.__isset.color) && ((!__isset.color) || (global::System.Object.Equals(Color, other.Color))))
        && ((__isset.hidden == other.__isset.hidden) && ((!__isset.hidden) || (global::System.Object.Equals(Hidden, other.Hidden))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.v)
        {
          hashcode = (hashcode * 397) + V.GetHashCode();
        }
        if((Color != null) && __isset.color)
        {
          hashcode = (hashcode * 397) + Color.GetHashCode();
        }
        if(__isset.hidden)
        {
          hashcode = (hashcode * 397) + Hidden.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp127 = new StringBuilder("Category(");
      int tmp128 = 0;
      if(__isset.v)
      {
        if(0 < tmp128++) { tmp127.Append(", "); }
        tmp127.Append("V: ");
        V.ToString(tmp127);
      }
      if((Color != null) && __isset.color)
      {
        if(0 < tmp128++) { tmp127.Append(", "); }
        tmp127.Append("Color: ");
        Color.ToString(tmp127);
      }
      if(__isset.hidden)
      {
        if(0 < tmp128++) { tmp127.Append(", "); }
        tmp127.Append("Hidden: ");
        Hidden.ToString(tmp127);
      }
      tmp127.Append(')');
      return tmp127.ToString();
    }
  }

}
