/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{

  public partial class Data : TBase
  {
    private global::Yaskawa.Ext.API.Series _sData;
    private global::Yaskawa.Ext.API.Category _cData;

    public global::Yaskawa.Ext.API.Series SData
    {
      get
      {
        return _sData;
      }
      set
      {
        __isset.sData = true;
        this._sData = value;
      }
    }

    public global::Yaskawa.Ext.API.Category CData
    {
      get
      {
        return _cData;
      }
      set
      {
        __isset.cData = true;
        this._cData = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool sData;
      public bool cData;
    }

    public Data()
    {
    }

    public Data DeepCopy()
    {
      var tmp134 = new Data();
      if((SData != null) && __isset.sData)
      {
        tmp134.SData = (global::Yaskawa.Ext.API.Series)this.SData.DeepCopy();
      }
      tmp134.__isset.sData = this.__isset.sData;
      if((CData != null) && __isset.cData)
      {
        tmp134.CData = (global::Yaskawa.Ext.API.Category)this.CData.DeepCopy();
      }
      tmp134.__isset.cData = this.__isset.cData;
      return tmp134;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                SData = new global::Yaskawa.Ext.API.Series();
                await SData.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                CData = new global::Yaskawa.Ext.API.Category();
                await CData.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp135 = new TStruct("Data");
        await oprot.WriteStructBeginAsync(tmp135, cancellationToken);
        var tmp136 = new TField();
        if((SData != null) && __isset.sData)
        {
          tmp136.Name = "sData";
          tmp136.Type = TType.Struct;
          tmp136.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
          await SData.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((CData != null) && __isset.cData)
        {
          tmp136.Name = "cData";
          tmp136.Type = TType.Struct;
          tmp136.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp136, cancellationToken);
          await CData.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Data other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.sData == other.__isset.sData) && ((!__isset.sData) || (global::System.Object.Equals(SData, other.SData))))
        && ((__isset.cData == other.__isset.cData) && ((!__isset.cData) || (global::System.Object.Equals(CData, other.CData))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((SData != null) && __isset.sData)
        {
          hashcode = (hashcode * 397) + SData.GetHashCode();
        }
        if((CData != null) && __isset.cData)
        {
          hashcode = (hashcode * 397) + CData.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp137 = new StringBuilder("Data(");
      int tmp138 = 0;
      if((SData != null) && __isset.sData)
      {
        if(0 < tmp138++) { tmp137.Append(", "); }
        tmp137.Append("SData: ");
        SData.ToString(tmp137);
      }
      if((CData != null) && __isset.cData)
      {
        if(0 < tmp138++) { tmp137.Append(", "); }
        tmp137.Append("CData: ");
        CData.ToString(tmp137);
      }
      tmp137.Append(')');
      return tmp137.ToString();
    }
  }

}
