/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{

  public partial class IllegalArgument : TException, TBase
  {

    public string Msg { get; set; }

    public IllegalArgument()
    {
    }

    public IllegalArgument(string msg) : this()
    {
      this.Msg = msg;
    }

    public IllegalArgument DeepCopy()
    {
      var tmp4 = new IllegalArgument();
      if((Msg != null))
      {
        tmp4.Msg = this.Msg;
      }
      return tmp4;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_msg = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                Msg = await iprot.ReadStringAsync(cancellationToken);
                isset_msg = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_msg)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp5 = new TStruct("IllegalArgument");
        await oprot.WriteStructBeginAsync(tmp5, cancellationToken);
        var tmp6 = new TField();
        if((Msg != null))
        {
          tmp6.Name = "msg";
          tmp6.Type = TType.String;
          tmp6.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp6, cancellationToken);
          await oprot.WriteStringAsync(Msg, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is IllegalArgument other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Msg, other.Msg);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Msg != null))
        {
          hashcode = (hashcode * 397) + Msg.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp7 = new StringBuilder("IllegalArgument(");
      if((Msg != null))
      {
        tmp7.Append(", Msg: ");
        Msg.ToString(tmp7);
      }
      tmp7.Append(')');
      return tmp7.ToString();
    }
  }

}
