/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{
  public enum IntegrationPoint
  {
    UtilityWindow = 0,
    NavigationPanel = 10,
    ProgrammingCommandBar = 20,
    ProgrammingHeaderBar = 30,
    SmartFrameJogPanelTopLeft = 40,
    SmartFrameJogPanelTopRight = 41,
    SmartFrameJogPanelTopAny = 44,
    SmartFrameJogPanelBottomLeft = 45,
    SmartFrameJogPanelBottomCenter = 46,
    SmartFrameJogPanelBottomRight = 47,
    SmartFrameJogPanelBottomAny = 49,
    JogPanelTopCenter = 50,
    HomeScreen = 60,
    JobTestPanelCenter = 70,
    JobTestPanelBottomLeft = 71,
    JobTestPanelBottomRight = 72,
    JobTestPanelTopLeft = 73,
    JobTestPanelTopRight = 74,
  }
}
