/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{
  /// <summary>
  /// Specify how to compute inverse kinematics (via transformPositionToFrame()):
  /// Delta: minimize joint coordinate distance between solution and provided Position
  /// Closure: try to match solution arm closure with provided Position
  /// Default: Use controller default method
  /// None: Not applicable/Do nothing
  /// </summary>
  public enum InverseKinematicsScheme
  {
    None = 0,
    Default = 1,
    Delta = 2,
    Closure = 3,
  }
}
