/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{
  /// <summary>
  /// Available motion types available when using GoToPositionButton
  /// * DefaultInterpolation - uses joint interpolation to move to joint coordinate position, and linear interpolation to move to Cartesian coordinate position.
  /// * JointInterpolation - uses joint interpolation (regardless of position coordinate system)
  /// * LinearInterpolation - uses linear interpolation (regardless of position coordinate system)
  /// (API version 3.1 and later)
  /// </summary>
  public enum MotionTypes
  {
    DefaultInterpolation = -1,
    JointInterpolation = 0,
    LinearInterpolation = 1,
  }
}
