/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{
  public enum PendantEventType
  {
    Startup = 0,
    Shutdown = 1,
    SwitchedScreen = 2,
    PopupOpened = 3,
    PopupClosed = 4,
    UtilityOpened = 5,
    UtilityClosed = 6,
    UtilityMoved = 7,
    Clicked = 8,
    Pressed = 9,
    Released = 10,
    TextEdited = 11,
    Accepted = 12,
    EditingFinished = 13,
    CheckedChanged = 14,
    Activated = 15,
    PanelOpened = 16,
    PanelClosed = 17,
    Canceled = 18,
    JoggingPanelVisibilityChanged = 19,
    VisibleChanged = 20,
    IntegrationPointSwitchStateChanged = 21,
    ValueChanged = 22,
    UtilityCreated = 23,
    UtilityDirectOpened = 24,
    Other = 16384,
  }
}
