/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Yaskawa.Ext.API
{

  public partial class PropQuery : TBase
  {

    public string ItemID { get; set; }

    public string Name { get; set; }

    public PropQuery()
    {
    }

    public PropQuery(string itemID, string name) : this()
    {
      this.ItemID = itemID;
      this.Name = name;
    }

    public PropQuery DeepCopy()
    {
      var tmp168 = new PropQuery();
      if((ItemID != null))
      {
        tmp168.ItemID = this.ItemID;
      }
      if((Name != null))
      {
        tmp168.Name = this.Name;
      }
      return tmp168;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_itemID = false;
        bool isset_name = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                ItemID = await iprot.ReadStringAsync(cancellationToken);
                isset_itemID = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Name = await iprot.ReadStringAsync(cancellationToken);
                isset_name = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_itemID)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_name)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp169 = new TStruct("PropQuery");
        await oprot.WriteStructBeginAsync(tmp169, cancellationToken);
        var tmp170 = new TField();
        if((ItemID != null))
        {
          tmp170.Name = "itemID";
          tmp170.Type = TType.String;
          tmp170.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp170, cancellationToken);
          await oprot.WriteStringAsync(ItemID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Name != null))
        {
          tmp170.Name = "name";
          tmp170.Type = TType.String;
          tmp170.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp170, cancellationToken);
          await oprot.WriteStringAsync(Name, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is PropQuery other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(ItemID, other.ItemID)
        && global::System.Object.Equals(Name, other.Name);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((ItemID != null))
        {
          hashcode = (hashcode * 397) + ItemID.GetHashCode();
        }
        if((Name != null))
        {
          hashcode = (hashcode * 397) + Name.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp171 = new StringBuilder("PropQuery(");
      if((ItemID != null))
      {
        tmp171.Append(", ItemID: ");
        ItemID.ToString(tmp171);
      }
      if((Name != null))
      {
        tmp171.Append(", Name: ");
        Name.ToString(tmp171);
      }
      tmp171.Append(')');
      return tmp171.ToString();
    }
  }

}
